packages:
  - '.'
  - 'resonai-mock'

overrides:
  fast-json-patch: '>=3.1.1'

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - protobufjs
  - unrs-resolver
