/**
 * ECRR KPI Calculator
 * Real-time metrics and analytics for ECRR automation system
 */

export interface KPI {
  id: string;
  name: string;
  value: number;
  unit: string;
  target?: number;
  status: 'good' | 'warning' | 'critical';
  trend: 'up' | 'down' | 'stable';
  trendPercentage?: number;
  description: string;
  lastUpdated: Date;
}

export interface KPIDashboard {
  overview: {
    totalReports: number;
    openReports: number;
    totalTasks: number;
    openTasks: number;
    overdueTasks: number;
    automationCoverage: number;
  };
  automation: {
    autoGeneratedTasks: number;
    manualTasks: number;
    automationCoveragePercent: number;
    averageTimeToTask: number;
  };
  performance: {
    averageTaskDuration: number;
    slaComplianceRate: number;
    escalationRate: number;
    reopenRate: number;
  };
  workload: {
    tasksByPriority: Record<string, number>;
    tasksByState: Record<string, number>;
    tasksByAssignee: Record<string, number>;
    wipUtilization: number;
  };
  trends: {
    reportsCreatedToday: number;
    tasksCompletedToday: number;
    slaBreachesToday: number;
    automationEventsToday: number;
  };
}

interface DatabaseInterface {
  getReportCount(filter?: any): Promise<number>;
  getTaskCount(filter?: any): Promise<number>;
  getTimeToTaskSamples(since: Date): Promise<Array<{timeToTask: number}>>;
  getTotalTaskDuration(since: Date): Promise<number>;
  getTaskCountByPriority(): Promise<Record<string, number>>;
  getTaskCountByState(): Promise<Record<string, number>>;
  getTaskCountByAssignee(): Promise<Record<string, number>>;
  getUsers(): Promise<any[]>;
  getEventCount(filter: any): Promise<number>;
}

export class KPICalculator {
  constructor(private db: DatabaseInterface) {} // Database interface

  /**
   * Calculate all KPIs for dashboard
   */
  async calculateDashboard(): Promise<KPIDashboard> {
    const [
      overview,
      automation,
      performance,
      workload,
      trends
    ] = await Promise.all([
      this.calculateOverview(),
      this.calculateAutomation(),
      this.calculatePerformance(),
      this.calculateWorkload(),
      this.calculateTrends()
    ]);

    return {
      overview,
      automation,
      performance,
      workload,
      trends
    };
  }

  /**
   * Calculate overview KPIs
   */
  async calculateOverview(): Promise<KPIDashboard['overview']> {
    const [
      totalReports,
      openReports,
      totalTasks,
      openTasks,
      overdueTasks
    ] = await Promise.all([
      this.db.getReportCount(),
      this.db.getReportCount({ status: 'Open' }),
      this.db.getTaskCount(),
      this.db.getTaskCount({ state: { $nin: ['DONE'] } }),
      this.db.getTaskCount({ 
        slaDueAt: { $lt: new Date() },
        state: { $nin: ['DONE'] }
      })
    ]);

    const automationCoverage = await this.calculateAutomationCoverage();

    return {
      totalReports,
      openReports,
      totalTasks,
      openTasks,
      overdueTasks,
      automationCoverage
    };
  }

  /**
   * Calculate automation KPIs
   */
  async calculateAutomation(): Promise<KPIDashboard['automation']> {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const [
      autoGeneratedTasks,
      manualTasks,
      timeToTaskSamples
    ] = await Promise.all([
      this.db.getTaskCount({
        'meta.autoGenerated': true,
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTaskCount({
        'meta.autoGenerated': { $ne: true },
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTimeToTaskSamples(thirtyDaysAgo)
    ]);

    const totalTasks = autoGeneratedTasks + manualTasks;
    const automationCoveragePercent = totalTasks > 0 
      ? Math.round((autoGeneratedTasks / totalTasks) * 100 * 100) / 100 
      : 0;

    const averageTimeToTask = timeToTaskSamples.length > 0
      ? timeToTaskSamples.reduce((sum: number, sample: any) => sum + sample.timeToTask, 0) / timeToTaskSamples.length
      : 0;

    return {
      autoGeneratedTasks,
      manualTasks,
      automationCoveragePercent,
      averageTimeToTask
    };
  }

  /**
   * Calculate performance KPIs
   */
  async calculatePerformance(): Promise<KPIDashboard['performance']> {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const [
      completedTasks,
      totalTaskTime,
      slaCompliantTasks,
      totalTasksWithSla,
      escalatedTasks,
      reopenedTasks
    ] = await Promise.all([
      this.db.getTaskCount({
        state: 'DONE',
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTotalTaskDuration(thirtyDaysAgo),
      this.db.getTaskCount({
        state: 'DONE',
        slaDueAt: { $exists: true },
        'meta.slaCompliant': true,
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTaskCount({
        state: 'DONE',
        slaDueAt: { $exists: true },
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTaskCount({
        'meta.escalated': true,
        createdAt: { $gte: thirtyDaysAgo }
      }),
      this.db.getTaskCount({
        'meta.reopened': true,
        createdAt: { $gte: thirtyDaysAgo }
      })
    ]);

    const averageTaskDuration = completedTasks > 0 
      ? totalTaskTime / completedTasks 
      : 0;

    const slaComplianceRate = totalTasksWithSla > 0
      ? Math.round((slaCompliantTasks / totalTasksWithSla) * 100 * 100) / 100
      : 100;

    const escalationRate = completedTasks > 0
      ? Math.round((escalatedTasks / completedTasks) * 100 * 100) / 100
      : 0;

    const reopenRate = completedTasks > 0
      ? Math.round((reopenedTasks / completedTasks) * 100 * 100) / 100
      : 0;

    return {
      averageTaskDuration,
      slaComplianceRate,
      escalationRate,
      reopenRate
    };
  }

  /**
   * Calculate workload KPIs
   */
  async calculateWorkload(): Promise<KPIDashboard['workload']> {
    const [
      tasksByPriority,
      tasksByState,
      tasksByAssignee,
      wipUtilization
    ] = await Promise.all([
      this.db.getTaskCountByPriority(),
      this.db.getTaskCountByState(),
      this.db.getTaskCountByAssignee(),
      this.calculateWipUtilization()
    ]);

    return {
      tasksByPriority,
      tasksByState,
      tasksByAssignee,
      wipUtilization
    };
  }

  /**
   * Calculate trend KPIs
   */
  async calculateTrends(): Promise<KPIDashboard['trends']> {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);

    const [
      reportsCreatedToday,
      tasksCompletedToday,
      slaBreachesToday,
      automationEventsToday
    ] = await Promise.all([
      this.db.getReportCount({
        createdAt: { $gte: today, $lt: tomorrow }
      }),
      this.db.getTaskCount({
        state: 'DONE',
        updatedAt: { $gte: today, $lt: tomorrow }
      }),
      this.db.getTaskCount({
        'meta.slaBreached': true,
        updatedAt: { $gte: today, $lt: tomorrow }
      }),
      this.db.getEventCount({
        type: { $in: ['TaskCreated', 'TaskUpdated', 'TaskStateChanged'] },
        occurredAt: { $gte: today, $lt: tomorrow }
      })
    ]);

    return {
      reportsCreatedToday,
      tasksCompletedToday,
      slaBreachesToday,
      automationEventsToday
    };
  }

  /**
   * Calculate automation coverage percentage
   */
  async calculateAutomationCoverage(): Promise<number> {
    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const autoTasks = await this.db.getTaskCount({
      'meta.autoGenerated': true,
      createdAt: { $gte: thirtyDaysAgo }
    });

    const totalTasks = await this.db.getTaskCount({
      createdAt: { $gte: thirtyDaysAgo }
    });

    return totalTasks > 0 ? Math.round((autoTasks / totalTasks) * 100 * 100) / 100 : 0;
  }

  /**
   * Calculate WIP utilization
   */
  async calculateWipUtilization(): Promise<number> {
    const users = await this.db.getUsers();
    const userWipData = await Promise.all(
      users.map(async (user: any) => {
        const currentWip = await this.db.getTaskCount({
          assignee: user.id,
          state: { $nin: ['DONE'] }
        });
        return {
          userId: user.id,
          currentWip,
          maxWip: user.maxWip
        };
      })
    );

    const totalCapacity = userWipData.reduce((sum, user) => sum + user.maxWip, 0);
    const totalCurrentWip = userWipData.reduce((sum, user) => sum + user.currentWip, 0);

    return totalCapacity > 0 
      ? Math.round((totalCurrentWip / totalCapacity) * 100 * 100) / 100 
      : 0;
  }

  /**
   * Get KPI trend data for charts
   */
  async getKPITrends(kpiId: string, days = 30): Promise<Array<{ date: string; value: number }>> {
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(startDate.getDate() - days);

    switch (kpiId) {
      case 'automation-coverage':
        return this.getAutomationCoverageTrend(startDate, endDate);
      case 'sla-compliance':
        return this.getSlaComplianceTrend(startDate, endDate);
      case 'average-task-duration':
        return this.getAverageTaskDurationTrend(startDate, endDate);
      case 'escalation-rate':
        return this.getEscalationRateTrend(startDate, endDate);
      default:
        return [];
    }
  }

  /**
   * Get automation coverage trend
   */
  private async getAutomationCoverageTrend(_startDate: Date, _endDate: Date): Promise<Array<{ date: string; value: number }>> {
    // Implementation would calculate daily automation coverage
    return [];
  }

  /**
   * Get SLA compliance trend
   */
  private async getSlaComplianceTrend(_startDate: Date, _endDate: Date): Promise<Array<{ date: string; value: number }>> {
    // Implementation would calculate daily SLA compliance
    return [];
  }

  /**
   * Get average task duration trend
   */
  private async getAverageTaskDurationTrend(_startDate: Date, _endDate: Date): Promise<Array<{ date: string; value: number }>> {
    // Implementation would calculate daily average task duration
    return [];
  }

  /**
   * Get escalation rate trend
   */
  private async getEscalationRateTrend(_startDate: Date, _endDate: Date): Promise<Array<{ date: string; value: number }>> {
    // Implementation would calculate daily escalation rate
    return [];
  }

  /**
   * Get critical alerts based on KPIs
   */
  async getCriticalAlerts(): Promise<Array<{
    id: string;
    type: 'warning' | 'critical';
    title: string;
    message: string;
    kpiId: string;
    currentValue: number;
    targetValue?: number;
    timestamp: Date;
  }>> {
    const alerts = [];
    const dashboard = await this.calculateDashboard();

    // Automation coverage alert
    if (dashboard.automation.automationCoveragePercent < 90) {
      alerts.push({
        id: 'automation-coverage-low',
        type: dashboard.automation.automationCoveragePercent < 70 ? 'critical' : 'warning',
        title: 'Low Automation Coverage',
        message: `Automation coverage is ${dashboard.automation.automationCoveragePercent}%, below target of 90%`,
        kpiId: 'automation-coverage',
        currentValue: dashboard.automation.automationCoveragePercent,
        targetValue: 90,
        timestamp: new Date()
      });
    }

    // SLA compliance alert
    if (dashboard.performance.slaComplianceRate < 95) {
      alerts.push({
        id: 'sla-compliance-low',
        type: dashboard.performance.slaComplianceRate < 85 ? 'critical' : 'warning',
        title: 'Low SLA Compliance',
        message: `SLA compliance is ${dashboard.performance.slaComplianceRate}%, below target of 95%`,
        kpiId: 'sla-compliance',
        currentValue: dashboard.performance.slaComplianceRate,
        targetValue: 95,
        timestamp: new Date()
      });
    }

    // High escalation rate alert
    if (dashboard.performance.escalationRate > 10) {
      alerts.push({
        id: 'escalation-rate-high',
        type: dashboard.performance.escalationRate > 20 ? 'critical' : 'warning',
        title: 'High Escalation Rate',
        message: `Escalation rate is ${dashboard.performance.escalationRate}%, above target of 10%`,
        kpiId: 'escalation-rate',
        currentValue: dashboard.performance.escalationRate,
        targetValue: 10,
        timestamp: new Date()
      });
    }

    // High reopen rate alert
    if (dashboard.performance.reopenRate > 5) {
      alerts.push({
        id: 'reopen-rate-high',
        type: dashboard.performance.reopenRate > 15 ? 'critical' : 'warning',
        title: 'High Reopen Rate',
        message: `Reopen rate is ${dashboard.performance.reopenRate}%, above target of 5%`,
        kpiId: 'reopen-rate',
        currentValue: dashboard.performance.reopenRate,
        targetValue: 5,
        timestamp: new Date()
      });
    }

    return alerts;
  }
}
