export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import TracingProvider from '../components/TracingProvider';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TracingProvider>
          {children}
        </TracingProvider>
      </body>
    </html>
  )
}
