extensions:
  health_check:
    endpoint: 0.0.0.0:13134
    path: /healthz

receivers:
  windows_event_log:
    - channel: Application
      log_name: Application
      start_at: end
      poll_interval: 1s
      exclude_providers:
        - Microsoft-Windows-Security-SPP
  filelog:
    - include: C:\logs\**\*.log
      start_at: end
      poll_interval: 1s
      operators:
        - type: json_parser
          parse_from: body
        - type: add
          field: log.source
          value: file
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 200ms
    send_batch_size: 256
  memory_limiter:
    check_interval: 5s
    limit_mib: 512
    spike_limit_mib: 128
  attributes/global:
    actions:
      - key: deployment.env
        value: local
        action: insert
  attributes/windows_event_log:
    include:
      match_type: instrumentation_scope
      instrumentation_scope_names: [otelcol/wineventlogreceiver]
    actions:
      - key: log.source
        value: windows_event_log
        action: insert

exporters:
  otlp/signoz:
    endpoint: localhost:14317
    tls:
      insecure: true
  otlphttp/signoz:
    endpoint: http://localhost:14318
    tls:
      insecure: true

service:
  extensions:
    - health_check
  telemetry:
    metrics:
      address: 0.0.0.0:8888
  pipelines:
    logs:
      receivers: [windows_event_log, filelog]
      processors: [memory_limiter, attributes/global, attributes/windows_event_log, batch]
      exporters: [otlp/signoz, otlphttp/signoz]
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/signoz, otlphttp/signoz]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/signoz, otlphttp/signoz]
