# scripts/agent/doctor.ps1
param(
  [switch]$VerboseOut
)

$ErrorActionPreference = "Stop"
$root = (Resolve-Path ".").Path
$agentDir = Join-Path $root ".agent"

function Section($name) { Write-Host "`n== $name ==" -ForegroundColor Cyan }
function Pass($msg)    { Write-Host ("[PASS] " + $msg) -ForegroundColor Green }
function Warn($msg)    { Write-Host ("[WARN] " + $msg) -ForegroundColor Yellow }
function Fail($msg)    { Write-Host ("[FAIL] " + $msg) -ForegroundColor Red }

$failed = $false

Section "Repo sanity"
try {
  $null = git rev-parse --is-inside-work-tree 2>$null
  if ($LASTEXITCODE -ne 0) { throw "Not a git repo" }
  $status = git status --porcelain
  Pass "Git repo detected"
  if ($status) { Warn "Working tree has changes (`"$($status.Split("`n").Length)`" file(s))" } else { Pass "Working tree clean" }
} catch {
  Fail "Git not ready: $($_.Exception.Message)"; $failed = $true
}

Section "Agent lock & config"
if (-not (Test-Path $agentDir)) { Fail "Missing .agent/ directory"; $failed = $true }
else {
  if (Test-Path (Join-Path $agentDir "LOCK")) {
    Fail ".agent/LOCK present — background agents are PAUSED. Remove to resume."
    $failed = $true
  } else {
    Pass "No kill-switch (.agent/LOCK) — agents allowed to run."
  }

  $cfgPath = Join-Path $agentDir "config.json"
  if (-not (Test-Path $cfgPath)) {
    Fail "Missing .agent/config.json (budgets undefined)"; $failed = $true
  } else {
    $cfg = Get-Content $cfgPath -Raw | ConvertFrom-Json
    $maxJobs  = $env:AGENT_MAX_JOBS  ? $env:AGENT_MAX_JOBS  : $cfg.maxJobs
    $maxFiles = $env:AGENT_MAX_FILES ? $env:AGENT_MAX_FILES : $cfg.maxFiles
    $maxLines = $env:AGENT_MAX_LINES ? $env:AGENT_MAX_LINES : $cfg.maxLines

    Pass ("Budgets => jobs:{0} files:{1} lines:{2}" -f $maxJobs, $maxFiles, $maxLines)
    if ($maxJobs -lt 1 -or $maxFiles -lt 1 -or $maxLines -lt 1) {
      Fail "Budget values invalid (must be >=1)"; $failed = $true
    }
  }

  foreach ($f in @("state.json","agent_queue.json")) {
    $p = Join-Path $agentDir $f
    if (-not (Test-Path $p)) { Warn "Missing .agent/$f — will be initialized on next run" } else { Pass "Found .agent/$f" }
  }
}

Section "Tooling & PATH"
# pnpm
$pnpmloc = (Get-Command pnpm -ErrorAction SilentlyContinue)
if (-not $pnpmloc) { Fail "pnpm not found on PATH"; $failed = $true } else { Pass "pnpm: $($pnpmloc.Path)" }
# Node
$node = (Get-Command node -ErrorAction SilentlyContinue)
if (-not $node) { Fail "node not found on PATH"; $failed = $true } else { Pass "node: $($node.Path)" }
# PowerShell edition
Pass ("Shell: {0} ({1})" -f $PSVersionTable.PSEdition, $PSVersionTable.PSVersion)

Section "SSOT & CI parity"
# Single Source of Truth / artifacts alignment
$ssot = Join-Path $root ".artifacts/SSOT.md"
if (-not (Test-Path $ssot)) {
  Warn "Missing .artifacts/SSOT.md (will be regenerated by agent/CI)"
} else {
  $age = (Get-Item $ssot).LastWriteTime
  Pass ("SSOT present (last update: {0})" -f $age)
}

# Quick Playwright config check
$pwConfigs = @()
$pwPaths = @("playwright.config.ts", "playwright.signoz.config.ts", "playwright.smoke.config.ts")
foreach ($pwPath in $pwPaths) {
  if (Test-Path (Join-Path $root $pwPath)) { $pwConfigs += $pwPath }
}
if ($pwConfigs.Count -gt 0) {
  Pass "Playwright configs: $($pwConfigs -join ', ')"
} else {
  Warn "No Playwright configs found"
}

Section "Summary"
if ($failed) {
  Write-Host "`nDoctor found issues. See FAIL items above." -ForegroundColor Red
  exit 1
} else {
  Write-Host "`nAll checks passed. Agents should be able to write when budgets & gates allow." -ForegroundColor Green
  exit 0
}