# SigNoz Canary Monitor Scheduled Action
# Generated by setup-canary-monitoring-schedule.ps1

Set-Location 'C:\otel\scripts'
$LogFile = 'C:\otel\scripts\..\artifacts\canary-monitor-schedule.log'
$Timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

try {
    # Run the monitor script
    $ExitCode = & 'C:\otel\scripts\monitor-signoz-canary.ps1'
    
    # Log the result
    $Status = switch ($ExitCode) {
        0 { 'HEALTHY' }
        1 { 'WARNING' }
        2 { 'CRITICAL' }
        3 { 'ERROR' }
        default { 'UNKNOWN' }
    }
    
    $LogEntry = "$Timestamp - Exit Code: $ExitCode, Status: $Status"
    Add-Content -Path $LogFile -Value $LogEntry
    
    # Send alert if not healthy
    if ($ExitCode -ne 0) {
        $AlertMessage = "SigNoz Canary Monitor Alert: Status=$Status, ExitCode=$ExitCode, Time=$Timestamp"
        Write-Host $AlertMessage -ForegroundColor Red
        
        # Email alert if configured
        if ('' -and '' -ne '') {
            try {
                Send-MailMessage -To '' -Subject "SigNoz Canary Alert" -Body $AlertMessage -SmtpServer "localhost"
            } catch {
                Write-Host "Failed to send email alert: $($_.Exception.Message)" -ForegroundColor Yellow
            }
        }
    }
    
    exit $ExitCode
} catch {
    $ErrorMsg = "Scheduled monitor failed: $($_.Exception.Message)"
    Add-Content -Path $LogFile -Value "$Timestamp - ERROR: $ErrorMsg"
    Write-Host $ErrorMsg -ForegroundColor Red
    exit 3
}
