# ECRR Compliance CI Integration Script
# This script can be used in CI/CD pipelines to validate ECRR compliance

param(
    [string]$ReportsDir = "docs/ECRR_REPORTS",
    [int]$MinFourSectionPct = 95,
    [int]$MinGatePct = 90,
    [string]$OutputJson = "artifacts/ecrr-ci-validation.json",
    [string]$OutputMarkdown = "artifacts/ecrr-ci-report.md",
    [switch]$FailOnThreshold = $true
)

$ErrorActionPreference = "Stop"

Write-Host "ECRR Compliance CI Check" -ForegroundColor Cyan
Write-Host "=======================" -ForegroundColor Cyan

# Ensure output directory exists
if (-not (Test-Path (Split-Path $OutputJson))) {
    New-Item -ItemType Directory -Path (Split-Path $OutputJson) -Force | Out-Null
}

# Run validation with FailOnThreshold enabled for CI
Write-Host "Running ECRR compliance validation..." -ForegroundColor Yellow
pwsh -File scripts/validate-ecrr-compliance.ps1 -ReportsDir $ReportsDir -OutJson $OutputJson -MinFourSectionPct $MinFourSectionPct -MinGatePct $MinGatePct

$validationResult = Get-Content $OutputJson | ConvertFrom-Json

# Generate markdown report
$statusIcon = if ($validationResult.passed) { '[PASS]' } else { '[FAIL]' }
$fourSectionIcon = if ($validationResult.fourSection.pct -ge $validationResult.thresholds.minFourSectionPct) { '[OK]' } else { '[FAIL]' }
$gateIcon = if ($validationResult.ecrrGate.pct -ge $validationResult.thresholds.minGatePct) { '[OK]' } else { '[FAIL]' }
$summaryText = if ($validationResult.passed) { 'All ECRR compliance checks passed! The repository maintains high standards for documentation and reporting.' } else { 'ECRR compliance is below thresholds. Please review and update ECRR reports to meet the required standards.' }
$nextStepsText = if ($validationResult.passed) { '- Continue maintaining ECRR compliance standards' } else { '- Review ECRR reports and ensure they follow the 4-section structure' + "`n" + '- Add ECRR Gate sections to reports missing them' + "`n" + '- Ensure all reports have proper actor declarations and evidence references' }

$report = @"
# ECRR Compliance CI Report

**Date**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")  
**Status**: $statusIcon

## Compliance Metrics

| Metric | Current | Threshold | Status |
|--------|---------|-----------|--------|
| Four-section Structure | $($validationResult.fourSection.pct)% ($($validationResult.fourSection.count)/$($validationResult.total)) | $($validationResult.thresholds.minFourSectionPct)% | $fourSectionIcon |
| ECRR Gates | $($validationResult.ecrrGate.pct)% ($($validationResult.ecrrGate.count)/$($validationResult.total)) | $($validationResult.thresholds.minGatePct)% | $gateIcon |

## Additional Metrics

- **Actor Declarations**: $($validationResult.actor)/$($validationResult.total) ($([math]::Round(($validationResult.actor / $validationResult.total) * 100, 1))%)
- **Evidence References**: $($validationResult.evidence)/$($validationResult.total) ($([math]::Round(($validationResult.evidence / $validationResult.total) * 100, 1))%)
- **Status Declarations**: $($validationResult.status)/$($validationResult.total) ($([math]::Round(($validationResult.status / $validationResult.total) * 100, 1))%)

## Summary

$summaryText

## Next Steps

$nextStepsText

---
*Generated by ECRR Compliance CI Check*
"@

$report | Out-File -FilePath $OutputMarkdown -Encoding UTF8

Write-Host "`nCompliance Check Results:" -ForegroundColor Yellow
Write-Host "========================" -ForegroundColor Yellow
Write-Host "Four-section Structure: $($validationResult.fourSection.pct)% ($($validationResult.fourSection.count)/$($validationResult.total))" -ForegroundColor White
Write-Host "ECRR Gates: $($validationResult.ecrrGate.pct)% ($($validationResult.ecrrGate.count)/$($validationResult.total))" -ForegroundColor White
Write-Host "Overall Status: $($validationResult.passed ? 'PASS' : 'FAIL')" -ForegroundColor $($validationResult.passed ? 'Green' : 'Red')

Write-Host "`nGenerated Files:" -ForegroundColor Cyan
Write-Host "- JSON Report: $OutputJson" -ForegroundColor White
Write-Host "- Markdown Report: $OutputMarkdown" -ForegroundColor White

# CI runs always fail on threshold violations
if (-not $validationResult.passed) {
    Write-Host "`n❌ ECRR compliance below thresholds - failing build" -ForegroundColor Red
    exit 1
} else {
    Write-Host "`n✅ ECRR compliance check completed successfully" -ForegroundColor Green
    exit 0
}
