# CI Integration Setup for ECRR Compliance
# This script provides instructions and examples for integrating ECRR compliance into CI/CD pipelines

param(
    [string]$OutputDir = "artifacts",
    [switch]$GenerateExamples = $true
)

$ErrorActionPreference = "Stop"

Write-Host "ECRR CI Integration Setup" -ForegroundColor Cyan
Write-Host "========================" -ForegroundColor Cyan

# Ensure output directory exists
if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
}

# Generate GitHub Actions workflow example
$githubActionsWorkflow = @"
name: ECRR Compliance Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run daily at 6 AM UTC
    - cron: '0 6 * * *'

jobs:
  ecrr-compliance:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PowerShell
      uses: PowerShell/PowerShell-For-GitHub-Actions@v1
      with:
        version: '7.4'
        
    - name: Run ECRR Compliance Check
      run: |
        pwsh -File scripts/ci-ecrr-compliance.ps1 -FailOnThreshold
      shell: pwsh
      
    - name: Upload Compliance Artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ecrr-compliance-report
        path: |
          artifacts/ecrr-ci-validation.json
          artifacts/ecrr-ci-report.md
        retention-days: 30
        
    - name: Comment PR with Compliance Status
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          try {
            const reportPath = 'artifacts/ecrr-ci-report.md';
            if (fs.existsSync(reportPath)) {
              const report = fs.readFileSync(reportPath, 'utf8');
              
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## ECRR Compliance Check Results\n\n${report}\n\n*This comment was automatically generated by the ECRR Compliance Check workflow.*`
              });
            }
          } catch (error) {
            console.log('Could not read compliance report:', error.message);
          }
"@

# Generate Azure DevOps pipeline example
$azureDevOpsPipeline = @"
trigger:
- main
- develop

pool:
  vmImage: 'windows-latest'

stages:
- stage: ECRRCompliance
  displayName: 'ECRR Compliance Check'
  jobs:
  - job: ComplianceCheck
    displayName: 'Run Compliance Check'
    steps:
    - task: PowerShell@2
      displayName: 'Run ECRR Compliance Check'
      inputs:
        filePath: 'scripts/ci-ecrr-compliance.ps1'
        arguments: '-FailOnThreshold'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Compliance Artifacts'
      inputs:
        pathToPublish: 'artifacts'
        artifactName: 'ecrr-compliance-report'
        publishLocation: 'Container'
"@

# Generate Jenkins pipeline example
$jenkinsPipeline = @"
pipeline {
    agent any
    
    triggers {
        cron('0 6 * * *')  // Daily at 6 AM
    }
    
    stages {
        stage('ECRR Compliance Check') {
            steps {
                script {
                    if (isUnix()) {
                        sh 'pwsh -File scripts/ci-ecrr-compliance.ps1 -FailOnThreshold'
                    } else {
                        powershell 'pwsh -File scripts/ci-ecrr-compliance.ps1 -FailOnThreshold'
                    }
                }
            }
        }
    }
    
    post {
        always {
            archiveArtifacts artifacts: 'artifacts/ecrr-ci-validation.json, artifacts/ecrr-ci-report.md', fingerprint: true
        }
    }
}
"@

# Generate setup instructions
$setupInstructions = @"
# ECRR CI Integration Setup Instructions

## Overview
This document provides instructions for integrating ECRR compliance checking into your CI/CD pipeline.

## Prerequisites
- PowerShell 7.4 or later
- ECRR compliance scripts in `scripts/` directory
- Artifacts directory for reports

## Integration Options

### 1. GitHub Actions
Copy the workflow from `$OutputDir/github-actions-workflow.yml` to `.github/workflows/ecrr-compliance.yml`

### 2. Azure DevOps
Copy the pipeline from `$OutputDir/azure-devops-pipeline.yml` to your Azure DevOps project

### 3. Jenkins
Copy the pipeline from `$OutputDir/jenkins-pipeline.yml` to your Jenkins job configuration

### 4. Local CI Script
Use `scripts/ci-ecrr-compliance.ps1` directly in your build scripts:

```powershell
# Run compliance check and fail on threshold violations
pwsh -File scripts/ci-ecrr-compliance.ps1 -FailOnThreshold

# Check exit code
if ($LASTEXITCODE -ne 0) {
    Write-Error "ECRR compliance check failed"
    exit 1
}
```

## Thresholds
- **Four-section Structure**: Minimum 95% (configurable via `-MinFourSectionPct`)
- **ECRR Gates**: Minimum 90% (configurable via `-MinGatePct`)

## Artifacts Generated
- `artifacts/ecrr-ci-validation.json` - Machine-readable compliance metrics
- `artifacts/ecrr-ci-report.md` - Human-readable compliance report

## Monitoring
- Set up alerts for compliance drops below thresholds
- Review compliance trends using `scripts/visualize-ecrr-trends.ps1`
- Schedule regular compliance monitoring (daily recommended)

## Troubleshooting
- Ensure PowerShell 7.4+ is available in CI environment
- Check that ECRR reports exist in `docs/ECRR_REPORTS/`
- Verify artifacts directory is writable
"@

if ($GenerateExamples) {
    Write-Host "Generating CI integration examples..." -ForegroundColor Yellow
    
    # Write example files
    $githubActionsWorkflow | Out-File -FilePath "$OutputDir/github-actions-workflow.yml" -Encoding UTF8
    $azureDevOpsPipeline | Out-File -FilePath "$OutputDir/azure-devops-pipeline.yml" -Encoding UTF8
    $jenkinsPipeline | Out-File -FilePath "$OutputDir/jenkins-pipeline.yml" -Encoding UTF8
    $setupInstructions | Out-File -FilePath "$OutputDir/ci-integration-setup.md" -Encoding UTF8
    
    Write-Host "`nGenerated CI Integration Files:" -ForegroundColor Green
    Write-Host "- $OutputDir/github-actions-workflow.yml" -ForegroundColor White
    Write-Host "- $OutputDir/azure-devops-pipeline.yml" -ForegroundColor White
    Write-Host "- $OutputDir/jenkins-pipeline.yml" -ForegroundColor White
    Write-Host "- $OutputDir/ci-integration-setup.md" -ForegroundColor White
}

Write-Host "`nCI Integration Setup Complete!" -ForegroundColor Green
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "1. Choose your CI platform and copy the appropriate workflow/pipeline" -ForegroundColor White
Write-Host "2. Test the integration with a test commit" -ForegroundColor White
Write-Host "3. Set up monitoring and alerts for compliance drops" -ForegroundColor White
