# Enhanced Scheduled Task with GPU Integration
# Generated by GPU Integration Automation

param(
    [switch]$IncludeGPU,
    [string]$TaskType = "monitoring"
)

Write-Host "⏰ Enhanced Scheduled Task: $TaskType" -ForegroundColor Cyan

# Load existing task logic
switch ($TaskType) {
    "monitoring" {
        # Run existing monitoring with GPU integration
        . "scripts/enhanced-monitoring-with-gpu.ps1" -IncludeGPU:$IncludeGPU -IncludeGPUMetrics:$IncludeGPU -IncludeGPUAlerts:$IncludeGPU
    }
    "health" {
        # Run existing health check with GPU integration
        . "scripts/gpu-workflow-orchestrator.ps1" -Action health
    }
    "canary" {
        # Run existing canary test with GPU integration
        . "scripts/canary-test.ps1"
        
        if ($IncludeGPU) {
            # Test GPU sidecar integration
            . "scripts/gpu-workflow-orchestrator.ps1" -Action test
        }
    }
}

Write-Host "⏰ Enhanced Scheduled Task Complete" -ForegroundColor Green
