# GPU-Enhanced Monitoring Script
# Generated by GPU Integration Automation

param(
    [switch]$IncludeGPU,
    [switch]$IncludeGPUMetrics,
    [switch]$IncludeGPUAlerts,
    [int]$DurationMinutes = 10
)

Write-Host "🔍 Enhanced Monitoring with GPU Integration" -ForegroundColor Cyan

# Load existing monitoring functions
. "scripts/monitor-optimized-pipeline.ps1"

function Test-GPUIntegration {
    Write-Host "
🎮 Testing GPU Integration..." -ForegroundColor Yellow
    
    # Test GPU sidecar health
    $gpuSidecars = @(
        @{Name="Compression"; Port=8001},
        @{Name="Aggregation"; Port=8002},
        @{Name="Inference"; Port=8003}
    )
    
    $gpuHealthy = 0
    foreach ($sidecar in $gpuSidecars) {
        try {
            $healthResponse = Invoke-WebRequest -Uri "http://localhost:$($sidecar.Port)/health" -UseBasicParsing -TimeoutSec 5
            if ($healthResponse.StatusCode -eq 200) {
                $healthData = $healthResponse.Content | ConvertFrom-Json
                Write-Host "   ✅ $($sidecar.Name): $($healthData.status)" -ForegroundColor Green
                if ($healthData.gpu_available) {
                    Write-Host "      🎮 GPU Available" -ForegroundColor Green
                }
                $gpuHealthy++
            } else {
                Write-Host "   ❌ $($sidecar.Name): HTTP $($healthResponse.StatusCode)" -ForegroundColor Red
            }
        } catch {
            Write-Host "   ❌ $($sidecar.Name): Not reachable" -ForegroundColor Red
        }
    }
    
    Write-Host "
🎮 GPU Integration: $gpuHealthy/$($gpuSidecars.Count) sidecars healthy" -ForegroundColor $(if($gpuHealthy -eq $gpuSidecars.Count){"Green"}else{"Yellow"})
    
    return $gpuHealthy -eq $gpuSidecars.Count
}

function Start-GPUMetricsCollection {
    if ($IncludeGPUMetrics) {
        Write-Host "
📊 Starting GPU Metrics Collection..." -ForegroundColor Yellow
        try {
            Start-Process -FilePath "python" -ArgumentList @("gpu-metrics-simple.py", "--duration", ($DurationMinutes * 60), "--interval", "15") -WindowStyle Hidden
            Write-Host "   ✅ GPU metrics collection started" -ForegroundColor Green
        } catch {
            Write-Host "   ❌ Failed to start GPU metrics collection: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
}

function Test-GPUAlerts {
    if ($IncludeGPUAlerts) {
        Write-Host "
🚨 Testing GPU Alerts..." -ForegroundColor Yellow
        
        # Test GPU alerting system
        try {
            $gpuMetrics = Get-Process -Name "python" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -match "gpu-metrics" }
            if ($gpuMetrics) {
                Write-Host "   ✅ GPU metrics collection active" -ForegroundColor Green
            } else {
                Write-Host "   ⚠️  GPU metrics collection not active" -ForegroundColor Yellow
            }
        } catch {
            Write-Host "   ❌ GPU alerting test failed: $($_.Exception.Message)" -ForegroundColor Red
        }
    }
}

# Main execution
if ($IncludeGPU) {
    Test-GPUIntegration
    Start-GPUMetricsCollection
    Test-GPUAlerts
}

Write-Host "
🔍 Enhanced Monitoring Complete" -ForegroundColor Green
