# GPU Integration Automation
# Integrates GPU sidecars into the existing automation workflow
# Provides seamless integration with monitoring, alerting, and reporting

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("integrate", "validate", "deploy", "monitor", "report", "cleanup")]
    [string]$Action,
    
    [switch]$IncludeExistingWorkflow,
    [switch]$IncludeScheduledTasks,
    [switch]$IncludeHealthChecks,
    [switch]$IncludeMetrics,
    [switch]$IncludeAlerts,
    [switch]$IncludeDashboard,
    [switch]$DryRun,
    [string]$Environment = "local"
)

# ECRR Framework Integration
$ECRRReport = @{
    Examine = @{}
    Clean = @{}
    Report = @{}
    Role = "GPU Integration Automation"
}

function Write-ECRRLog {
    param([string]$Message, [string]$Level = "INFO")
    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
    $logEntry = "[$timestamp] [$Level] $Message"
    Write-Host $logEntry -ForegroundColor $(if($Level -eq "ERROR"){"Red"}elseif($Level -eq "WARN"){"Yellow"}else{"Green"})
    $ECRRReport.Report[$timestamp] = $logEntry
}

function Test-ExistingWorkflowIntegration {
    Write-ECRRLog "Examining existing workflow integration..."
    
    $integration = @{
        scheduled_tasks = @{}
        monitoring_scripts = @{}
        health_checks = @{}
        alerting_systems = @{}
        dashboards = @{}
    }
    
    # Check existing scheduled tasks
    try {
        $existingTasks = Get-ScheduledTask -TaskName "*OTel*" -ErrorAction SilentlyContinue
        $integration.scheduled_tasks.count = $existingTasks.Count
        $integration.scheduled_tasks.tasks = $existingTasks | Select-Object TaskName, State
        Write-ECRRLog "Found $($existingTasks.Count) existing OTel scheduled tasks"
    } catch {
        Write-ECRRLog "Failed to check scheduled tasks: $($_.Exception.Message)" "ERROR"
    }
    
    # Check monitoring scripts
    $monitoringScripts = @(
        "scripts/monitor-optimized-pipeline.ps1",
        "scripts/quick-monitor.ps1",
        "scripts/production-monitoring.ps1",
        "scripts/robust-production-monitor.ps1"
    )
    
    foreach ($script in $monitoringScripts) {
        if (Test-Path $script) {
            $integration.monitoring_scripts[$script] = $true
            Write-ECRRLog "Found monitoring script: $script"
        }
    }
    
    # Check health check endpoints
    $healthEndpoints = @(
        @{Name="Collector"; URL="http://localhost:13134/healthz"},
        @{Name="SigNoz"; URL="http://localhost:8080/api/v1/health"},
        @{Name="GPU Compression"; URL="http://localhost:8001/health"},
        @{Name="GPU Aggregation"; URL="http://localhost:8002/health"},
        @{Name="GPU Inference"; URL="http://localhost:8003/health"}
    )
    
    foreach ($endpoint in $healthEndpoints) {
        try {
            $response = Invoke-WebRequest -Uri $endpoint.URL -UseBasicParsing -TimeoutSec 5
            $integration.health_checks[$endpoint.Name] = @{healthy = $true; status_code = $response.StatusCode}
            Write-ECRRLog "$($endpoint.Name) health check: HEALTHY"
        } catch {
            $integration.health_checks[$endpoint.Name] = @{healthy = $false; error = $_.Exception.Message}
            Write-ECRRLog "$($endpoint.Name) health check: UNHEALTHY" "ERROR"
        }
    }
    
    # Check alerting systems
    $alertingFiles = @(
        "alerts/signoz-alerts.json",
        "signoz-ecrr-canary-alert.json",
        "signoz-health-canary-alert.json",
        "signoz-metrics-canary-alert.json"
    )
    
    foreach ($file in $alertingFiles) {
        if (Test-Path $file) {
            $integration.alerting_systems[$file] = $true
            Write-ECRRLog "Found alerting configuration: $file"
        }
    }
    
    # Check dashboard configurations
    $dashboardFiles = @(
        "artifacts/signoz-gpu-sidecar-dashboard.json",
        "artifacts/signoz-dashboard-config.json"
    )
    
    foreach ($file in $dashboardFiles) {
        if (Test-Path $file) {
            $integration.dashboards[$file] = $true
            Write-ECRRLog "Found dashboard configuration: $file"
        }
    }
    
    $ECRRReport.Examine.Integration = $integration
    return $integration
}

function Integrate-GPUWithExistingWorkflow {
    param([hashtable]$Integration)
    
    Write-ECRRLog "Integrating GPU sidecars with existing workflow..."
    
    if ($DryRun) {
        Write-ECRRLog "DRY RUN: Would integrate GPU with existing workflow"
        return $true
    }
    
    # Integrate with monitoring scripts
    $monitoringIntegrationScript = @"
# GPU-Enhanced Monitoring Script
# Generated by GPU Integration Automation

param(
    [switch]`$IncludeGPU,
    [switch]`$IncludeGPUMetrics,
    [switch]`$IncludeGPUAlerts,
    [int]`$DurationMinutes = 10
)

Write-Host "🔍 Enhanced Monitoring with GPU Integration" -ForegroundColor Cyan

# Load existing monitoring functions
. "scripts/monitor-optimized-pipeline.ps1"

function Test-GPUIntegration {
    Write-Host "`n🎮 Testing GPU Integration..." -ForegroundColor Yellow
    
    # Test GPU sidecar health
    `$gpuSidecars = @(
        @{Name="Compression"; Port=8001},
        @{Name="Aggregation"; Port=8002},
        @{Name="Inference"; Port=8003}
    )
    
    `$gpuHealthy = 0
    foreach (`$sidecar in `$gpuSidecars) {
        try {
            `$healthResponse = Invoke-WebRequest -Uri "http://localhost:`$(`$sidecar.Port)/health" -UseBasicParsing -TimeoutSec 5
            if (`$healthResponse.StatusCode -eq 200) {
                `$healthData = `$healthResponse.Content | ConvertFrom-Json
                Write-Host "   ✅ `$(`$sidecar.Name): `$(`$healthData.status)" -ForegroundColor Green
                if (`$healthData.gpu_available) {
                    Write-Host "      🎮 GPU Available" -ForegroundColor Green
                }
                `$gpuHealthy++
            } else {
                Write-Host "   ❌ `$(`$sidecar.Name): HTTP `$(`$healthResponse.StatusCode)" -ForegroundColor Red
            }
        } catch {
            Write-Host "   ❌ `$(`$sidecar.Name): Not reachable" -ForegroundColor Red
        }
    }
    
    Write-Host "`n🎮 GPU Integration: `$gpuHealthy/`$(`$gpuSidecars.Count) sidecars healthy" -ForegroundColor `$(if(`$gpuHealthy -eq `$gpuSidecars.Count){"Green"}else{"Yellow"})
    
    return `$gpuHealthy -eq `$gpuSidecars.Count
}

function Start-GPUMetricsCollection {
    if (`$IncludeGPUMetrics) {
        Write-Host "`n📊 Starting GPU Metrics Collection..." -ForegroundColor Yellow
        try {
            Start-Process -FilePath "python" -ArgumentList @("gpu-metrics-simple.py", "--duration", (`$DurationMinutes * 60), "--interval", "15") -WindowStyle Hidden
            Write-Host "   ✅ GPU metrics collection started" -ForegroundColor Green
        } catch {
            Write-Host "   ❌ Failed to start GPU metrics collection: `$(`$_.Exception.Message)" -ForegroundColor Red
        }
    }
}

function Test-GPUAlerts {
    if (`$IncludeGPUAlerts) {
        Write-Host "`n🚨 Testing GPU Alerts..." -ForegroundColor Yellow
        
        # Test GPU alerting system
        try {
            `$gpuMetrics = Get-Process -Name "python" -ErrorAction SilentlyContinue | Where-Object { `$_.CommandLine -match "gpu-metrics" }
            if (`$gpuMetrics) {
                Write-Host "   ✅ GPU metrics collection active" -ForegroundColor Green
            } else {
                Write-Host "   ⚠️  GPU metrics collection not active" -ForegroundColor Yellow
            }
        } catch {
            Write-Host "   ❌ GPU alerting test failed: `$(`$_.Exception.Message)" -ForegroundColor Red
        }
    }
}

# Main execution
if (`$IncludeGPU) {
    Test-GPUIntegration
    Start-GPUMetricsCollection
    Test-GPUAlerts
}

Write-Host "`n🔍 Enhanced Monitoring Complete" -ForegroundColor Green
"@
    
    $monitoringIntegrationScript | Out-File -FilePath "scripts/enhanced-monitoring-with-gpu.ps1" -Encoding UTF8
    Write-ECRRLog "Created GPU-enhanced monitoring script"
    
    # Integrate with existing scheduled tasks
    if ($Integration.scheduled_tasks.count -gt 0) {
        Write-ECRRLog "Integrating GPU monitoring with existing scheduled tasks..."
        
        $enhancedTaskScript = @"
# Enhanced Scheduled Task with GPU Integration
# Generated by GPU Integration Automation

param(
    [switch]`$IncludeGPU,
    [string]`$TaskType = "monitoring"
)

Write-Host "⏰ Enhanced Scheduled Task: `$TaskType" -ForegroundColor Cyan

# Load existing task logic
switch (`$TaskType) {
    "monitoring" {
        # Run existing monitoring with GPU integration
        . "scripts/enhanced-monitoring-with-gpu.ps1" -IncludeGPU:`$IncludeGPU -IncludeGPUMetrics:`$IncludeGPU -IncludeGPUAlerts:`$IncludeGPU
    }
    "health" {
        # Run existing health check with GPU integration
        . "scripts/gpu-workflow-orchestrator.ps1" -Action health
    }
    "canary" {
        # Run existing canary test with GPU integration
        . "scripts/canary-test.ps1"
        
        if (`$IncludeGPU) {
            # Test GPU sidecar integration
            . "scripts/gpu-workflow-orchestrator.ps1" -Action test
        }
    }
}

Write-Host "⏰ Enhanced Scheduled Task Complete" -ForegroundColor Green
"@
        
        $enhancedTaskScript | Out-File -FilePath "scripts/enhanced-scheduled-task.ps1" -Encoding UTF8
        Write-ECRRLog "Created GPU-enhanced scheduled task script"
    }
    
    # Integrate with alerting systems
    if ($Integration.alerting_systems.Count -gt 0) {
        Write-ECRRLog "Integrating GPU alerts with existing alerting system..."
        
        $gpuAlertConfig = @{
            alerts = @(
                @{
                    name = "GPU Sidecar Health"
                    description = "GPU sidecar service health check"
                    query = "gpu.sidecar.health == 0"
                    threshold = 1
                    duration = "5m"
                    severity = "critical"
                },
                @{
                    name = "GPU Temperature High"
                    description = "GPU temperature exceeds safe threshold"
                    query = "gpu.temperature.celsius > 85"
                    threshold = 1
                    duration = "2m"
                    severity = "warning"
                },
                @{
                    name = "GPU Memory Usage High"
                    description = "GPU memory usage exceeds 90%"
                    query = "gpu.memory.utilization.percent > 90"
                    threshold = 1
                    duration = "5m"
                    severity = "warning"
                }
            )
        }
        
        $gpuAlertConfig | ConvertTo-Json -Depth 5 | Out-File -FilePath "alerts/gpu-alerts.json" -Encoding UTF8
        Write-ECRRLog "Created GPU alerting configuration"
    }
    
    return $true
}

function Validate-GPUIntegration {
    Write-ECRRLog "Validating GPU integration..."
    
    $validation = @{
        sidecar_health = @{}
        workflow_integration = @{}
        monitoring_integration = @{}
        alerting_integration = @{}
        dashboard_integration = @{}
    }
    
    # Validate sidecar health
    $sidecars = @(
        @{Name="Compression"; Port=8001},
        @{Name="Aggregation"; Port=8002},
        @{Name="Inference"; Port=8003}
    )
    
    foreach ($sidecar in $sidecars) {
        try {
            $healthResponse = Invoke-WebRequest -Uri "http://localhost:$($sidecar.Port)/health" -UseBasicParsing -TimeoutSec 5
            if ($healthResponse.StatusCode -eq 200) {
                $healthData = $healthResponse.Content | ConvertFrom-Json
                $validation.sidecar_health[$sidecar.Name] = @{
                    healthy = $true
                    status = $healthData.status
                    gpu_available = $healthData.gpu_available
                }
            } else {
                $validation.sidecar_health[$sidecar.Name] = @{healthy = $false; error = "HTTP $($healthResponse.StatusCode)"}
            }
        } catch {
            $validation.sidecar_health[$sidecar.Name] = @{healthy = $false; error = $_.Exception.Message}
        }
    }
    
    # Validate workflow integration
    $workflowFiles = @(
        "scripts/enhanced-monitoring-with-gpu.ps1",
        "scripts/enhanced-scheduled-task.ps1"
    )
    
    foreach ($file in $workflowFiles) {
        $validation.workflow_integration[$file] = Test-Path $file
    }
    
    # Validate monitoring integration
    try {
        $monitoringTest = & pwsh -ExecutionPolicy Bypass -File "scripts/enhanced-monitoring-with-gpu.ps1" -IncludeGPU -DurationMinutes 1
        $validation.monitoring_integration.enhanced_script = $LASTEXITCODE -eq 0
    } catch {
        $validation.monitoring_integration.enhanced_script = $false
        $validation.monitoring_integration.error = $_.Exception.Message
    }
    
    # Validate alerting integration
    $validation.alerting_integration.gpu_alerts_config = Test-Path "alerts/gpu-alerts.json"
    
    # Validate dashboard integration
    $validation.dashboard_integration.gpu_dashboard = Test-Path "artifacts/signoz-gpu-sidecar-dashboard.json"
    
    $ECRRReport.Examine.Validation = $validation
    
    # Calculate overall validation score
    $totalChecks = 0
    $passedChecks = 0
    
    foreach ($category in $validation.Keys) {
        if ($validation[$category] -is [hashtable]) {
            foreach ($check in $validation[$category].Keys) {
                $totalChecks++
                if ($validation[$category][$check] -is [hashtable]) {
                    if ($validation[$category][$check].healthy) { $passedChecks++ }
                } elseif ($validation[$category][$check] -eq $true) {
                    $passedChecks++
                }
            }
        }
    }
    
    $validationScore = if ($totalChecks -gt 0) { ($passedChecks / $totalChecks) * 100 } else { 0 }
    Write-ECRRLog "GPU integration validation: $($validationScore.ToString('F1'))% ($passedChecks/$totalChecks checks passed)"
    
    return @{validation = $validation; score = $validationScore; passed = $passedChecks; total = $totalChecks}
}

function Deploy-GPUIntegration {
    Write-ECRRLog "Deploying GPU integration..."
    
    if ($DryRun) {
        Write-ECRRLog "DRY RUN: Would deploy GPU integration"
        return $true
    }
    
    # Deploy GPU sidecars
    try {
        $deployResult = docker-compose -f docker-compose.gpu.yml up -d
        if ($LASTEXITCODE -eq 0) {
            Write-ECRRLog "GPU sidecars deployed successfully"
        } else {
            Write-ECRRLog "GPU sidecar deployment failed" "ERROR"
            return $false
        }
    } catch {
        Write-ECRRLog "GPU sidecar deployment error: $($_.Exception.Message)" "ERROR"
        return $false
    }
    
    # Deploy enhanced monitoring
    if ($IncludeHealthChecks) {
        try {
            Start-Process -FilePath "pwsh" -ArgumentList @("-ExecutionPolicy", "Bypass", "-File", "scripts/enhanced-monitoring-with-gpu.ps1", "-IncludeGPU", "-IncludeGPUMetrics") -WindowStyle Hidden
            Write-ECRRLog "Enhanced monitoring deployed"
        } catch {
            Write-ECRRLog "Failed to deploy enhanced monitoring: $($_.Exception.Message)" "ERROR"
        }
    }
    
    # Deploy GPU metrics collection
    if ($IncludeMetrics) {
        try {
            Start-Process -FilePath "python" -ArgumentList @("gpu-metrics-simple.py", "--duration", "3600", "--interval", "15") -WindowStyle Hidden
            Write-ECRRLog "GPU metrics collection deployed"
        } catch {
            Write-ECRRLog "Failed to deploy GPU metrics collection: $($_.Exception.Message)" "ERROR"
        }
    }
    
    # Deploy GPU alerting
    if ($IncludeAlerts) {
        try {
            Start-Process -FilePath "pwsh" -ArgumentList @("-ExecutionPolicy", "Bypass", "-File", "scripts/gpu-automated-monitoring.ps1", "-EnableAlerting") -WindowStyle Hidden
            Write-ECRRLog "GPU alerting deployed"
        } catch {
            Write-ECRRLog "Failed to deploy GPU alerting: $($_.Exception.Message)" "ERROR"
        }
    }
    
    # Deploy GPU dashboard
    if ($IncludeDashboard) {
        try {
            $dashboardResult = & pwsh -ExecutionPolicy Bypass -File "scripts/import-dashboard.ps1" -DashboardFile "artifacts/signoz-gpu-sidecar-dashboard.json"
            if ($LASTEXITCODE -eq 0) {
                Write-ECRRLog "GPU dashboard deployed"
            } else {
                Write-ECRRLog "GPU dashboard deployment failed" "ERROR"
            }
        } catch {
            Write-ECRRLog "GPU dashboard deployment error: $($_.Exception.Message)" "ERROR"
        }
    }
    
    return $true
}

function Start-GPUIntegrationMonitoring {
    Write-ECRRLog "Starting GPU integration monitoring..."
    
    $monitoringScript = @"
# GPU Integration Monitoring
# Generated by GPU Integration Automation

`$LogPath = "artifacts\gpu-integration-monitor-`$(Get-Date -Format 'yyyyMMdd_HHmmss').log"

Write-Host "🎮 Starting GPU Integration Monitoring" -ForegroundColor Cyan

# Create log file
"GPU Integration Monitoring Started - `$(Get-Date)" | Out-File -FilePath `$LogPath -Encoding UTF8

while (`$true) {
    `$timestamp = Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ'
    
    try {
        # Check GPU sidecar integration
        `$sidecars = @(
            @{Name="Compression"; Port=8001},
            @{Name="Aggregation"; Port=8002},
            @{Name="Inference"; Port=8003}
        )
        
        `$healthyCount = 0
        foreach (`$sidecar in `$sidecars) {
            try {
                `$healthResponse = Invoke-WebRequest -Uri "http://localhost:`$(`$sidecar.Port)/health" -UseBasicParsing -TimeoutSec 5
                if (`$healthResponse.StatusCode -eq 200) {
                    `$healthyCount++
                }
            } catch {
                # Sidecar unhealthy
            }
        }
        
        `$integrationHealth = if (`$healthyCount -eq `$sidecars.Count) { "HEALTHY" } else { "DEGRADED" }
        
        Write-Host "`[$timestamp`] GPU Integration: `$integrationHealth (`$healthyCount/`$(`$sidecars.Count) sidecars)" -ForegroundColor `$(if(`$integrationHealth -eq "HEALTHY"){"Green"}else{"Yellow"})
        "`$timestamp - GPU Integration: `$integrationHealth (`$healthyCount/`$(`$sidecars.Count) sidecars)" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
        
        # Check workflow integration
        try {
            `$workflowFiles = @(
                "scripts/enhanced-monitoring-with-gpu.ps1",
                "scripts/enhanced-scheduled-task.ps1"
            )
            
            `$workflowHealthy = `$true
            foreach (`$file in `$workflowFiles) {
                if (-not (Test-Path `$file)) {
                    `$workflowHealthy = `$false
                    break
                }
            }
            
            `$workflowStatus = if (`$workflowHealthy) { "INTEGRATED" } else { "MISSING_FILES" }
            Write-Host "`[$timestamp`] Workflow Integration: `$workflowStatus" -ForegroundColor `$(if(`$workflowStatus -eq "INTEGRATED"){"Green"}else{"Red"})
            "`$timestamp - Workflow Integration: `$workflowStatus" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
            
        } catch {
            Write-Host "`[$timestamp`] Workflow Integration: ERROR - `$(`$_.Exception.Message)" -ForegroundColor Red
            "`$timestamp - Workflow Integration: ERROR - `$(`$_.Exception.Message)" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
        }
        
        # Check alerting integration
        try {
            `$alertConfigExists = Test-Path "alerts/gpu-alerts.json"
            `$alertStatus = if (`$alertConfigExists) { "CONFIGURED" } else { "MISSING_CONFIG" }
            Write-Host "`[$timestamp`] Alerting Integration: `$alertStatus" -ForegroundColor `$(if(`$alertStatus -eq "CONFIGURED"){"Green"}else{"Yellow"})
            "`$timestamp - Alerting Integration: `$alertStatus" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
            
        } catch {
            Write-Host "`[$timestamp`] Alerting Integration: ERROR - `$(`$_.Exception.Message)" -ForegroundColor Red
            "`$timestamp - Alerting Integration: ERROR - `$(`$_.Exception.Message)" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
        }
        
    } catch {
        Write-Host "`[$timestamp`] GPU Integration Monitoring Error: `$(`$_.Exception.Message)" -ForegroundColor Red
        "`$timestamp - GPU Integration Monitoring Error: `$(`$_.Exception.Message)" | Out-File -FilePath `$LogPath -Append -Encoding UTF8
    }
    
    Start-Sleep -Seconds 60  # Check every minute
}
"@
    
    $monitoringScript | Out-File -FilePath ".artifacts/gpu-integration-monitor.ps1" -Encoding UTF8
    Write-ECRRLog "Created GPU integration monitoring script"
    
    if ($DryRun) {
        Write-ECRRLog "DRY RUN: Would start GPU integration monitoring"
    } else {
        Start-Process -FilePath "pwsh" -ArgumentList @("-ExecutionPolicy", "Bypass", "-File", ".artifacts/gpu-integration-monitor.ps1") -WindowStyle Hidden
        Write-ECRRLog "Started GPU integration monitoring"
    }
}

function Generate-GPUIntegrationReport {
    Write-ECRRLog "Generating GPU integration report..."
    
    $report = @{
        timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:ssZ"
        environment = $Environment
        integration_status = @{}
        performance_metrics = @{}
        recommendations = @()
    }
    
    # Integration status
    $integration = Test-ExistingWorkflowIntegration
    $report.integration_status = $integration
    
    # Performance metrics
    try {
        $sidecars = @("Compression", "Aggregation", "Inference")
        $ports = @(8001, 8002, 8003)
        
        for ($i = 0; $i -lt $sidecars.Count; $i++) {
            try {
                $healthResponse = Invoke-WebRequest -Uri "http://localhost:$($ports[$i])/health" -UseBasicParsing -TimeoutSec 5
                if ($healthResponse.StatusCode -eq 200) {
                    $healthData = $healthResponse.Content | ConvertFrom-Json
                    $report.performance_metrics[$sidecars[$i]] = @{
                        healthy = $true
                        response_time = $healthResponse.Headers.'X-Response-Time'
                        gpu_available = $healthData.gpu_available
                    }
                }
            } catch {
                $report.performance_metrics[$sidecars[$i]] = @{healthy = $false; error = $_.Exception.Message}
            }
        }
    } catch {
        Write-ECRRLog "Failed to collect performance metrics: $($_.Exception.Message)" "ERROR"
    }
    
    # Generate recommendations
    if ($integration.health_checks.Values | Where-Object { -not $_.healthy }) {
        $report.recommendations += "Fix unhealthy GPU sidecar services"
    }
    
    if ($integration.scheduled_tasks.count -eq 0) {
        $report.recommendations += "Set up scheduled tasks for automated monitoring"
    }
    
    if ($integration.alerting_systems.Count -eq 0) {
        $report.recommendations += "Configure alerting system for GPU monitoring"
    }
    
    if ($integration.dashboards.Count -eq 0) {
        $report.recommendations += "Import GPU dashboard to SigNoz"
    }
    
    # Save report
    $reportFile = "artifacts/gpu-integration-report-$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
    $report | ConvertTo-Json -Depth 5 | Out-File -FilePath $reportFile -Encoding UTF8
    
    # Generate HTML report
    $htmlReport = @"
<!DOCTYPE html>
<html>
<head>
    <title>GPU Integration Report</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background: #f0f0f0; padding: 20px; border-radius: 5px; }
        .section { margin: 20px 0; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }
        .healthy { color: green; }
        .unhealthy { color: red; }
        .warning { color: orange; }
        .recommendation { background: #fff3cd; padding: 10px; margin: 5px 0; border-radius: 3px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>🎮 GPU Integration Report</h1>
        <p>Generated: $($report.timestamp)</p>
        <p>Environment: $($report.environment)</p>
    </div>
    
    <div class="section">
        <h2>📊 Integration Status</h2>
        <p>Scheduled Tasks: $($report.integration_status.scheduled_tasks.count)</p>
        <p>Monitoring Scripts: $($report.integration_status.monitoring_scripts.Count)</p>
        <p>Health Checks: $($report.integration_status.health_checks.Count)</p>
        <p>Alerting Systems: $($report.integration_status.alerting_systems.Count)</p>
        <p>Dashboards: $($report.integration_status.dashboards.Count)</p>
    </div>
    
    <div class="section">
        <h2>🎮 GPU Sidecar Performance</h2>
"@
    
    foreach ($sidecar in $report.performance_metrics.Keys) {
        $metrics = $report.performance_metrics[$sidecar]
        $statusClass = if ($metrics.healthy) { "healthy" } else { "unhealthy" }
        $htmlReport += "<p class=`"$statusClass`">$sidecar`: $(if($metrics.healthy){'HEALTHY'}else{'UNHEALTHY'})</p>"
    }
    
    $htmlReport += @"
    </div>
    
    <div class="section">
        <h2>💡 Recommendations</h2>
"@
    
    foreach ($recommendation in $report.recommendations) {
        $htmlReport += "<div class=`"recommendation`">$recommendation</div>"
    }
    
    $htmlReport += @"
    </div>
</body>
</html>
"@
    
    $htmlReportFile = $reportFile -replace '\.json$', '.html'
    $htmlReport | Out-File -FilePath $htmlReportFile -Encoding UTF8
    
    Write-ECRRLog "GPU integration report generated: $reportFile"
    Write-ECRRLog "HTML report generated: $htmlReportFile"
    
    return $report
}

function Cleanup-GPUIntegration {
    Write-ECRRLog "Cleaning up GPU integration..."
    
    if ($DryRun) {
        Write-ECRRLog "DRY RUN: Would clean up GPU integration"
        return $true
    }
    
    # Stop GPU sidecars
    try {
        docker-compose -f docker-compose.gpu.yml down
        Write-ECRRLog "GPU sidecars stopped"
    } catch {
        Write-ECRRLog "Failed to stop GPU sidecars: $($_.Exception.Message)" "ERROR"
    }
    
    # Stop monitoring processes
    try {
        $gpuProcesses = Get-Process -Name "pwsh" -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -match "gpu" }
        foreach ($process in $gpuProcesses) {
            $process.Kill()
            Write-ECRRLog "Stopped GPU monitoring process (PID: $($process.Id))"
        }
    } catch {
        Write-ECRRLog "No GPU monitoring processes to stop" "WARN"
    }
    
    # Clean up temporary files
    $tempFiles = @(
        ".artifacts/gpu-*.ps1",
        ".artifacts/gpu-*.log",
        "gpu-buffers/logs/test-*.jsonl"
    )
    
    foreach ($pattern in $tempFiles) {
        try {
            Get-ChildItem -Path $pattern -ErrorAction SilentlyContinue | Remove-Item -Force
            Write-ECRRLog "Cleaned up temporary files: $pattern"
        } catch {
            Write-ECRRLog "No files to clean up: $pattern" "WARN"
        }
    }
    
    return $true
}

# Main execution
Write-Host "🔗 GPU Integration Automation" -ForegroundColor Cyan
Write-Host "=============================" -ForegroundColor Cyan
Write-Host "Action: $Action" -ForegroundColor Yellow
Write-Host "Environment: $Environment" -ForegroundColor Yellow
Write-Host "Include Existing Workflow: $IncludeExistingWorkflow" -ForegroundColor Yellow
Write-Host "Include Scheduled Tasks: $IncludeScheduledTasks" -ForegroundColor Yellow
Write-Host "Include Health Checks: $IncludeHealthChecks" -ForegroundColor Yellow
Write-Host "Include Metrics: $IncludeMetrics" -ForegroundColor Yellow
Write-Host "Include Alerts: $IncludeAlerts" -ForegroundColor Yellow
Write-Host "Include Dashboard: $IncludeDashboard" -ForegroundColor Yellow
Write-Host "Dry Run: $DryRun" -ForegroundColor Yellow
Write-Host ""

switch ($Action) {
    "integrate" {
        # ECRR: Examine
        $integration = Test-ExistingWorkflowIntegration
        
        # ECRR: Clean
        $integrateResult = Integrate-GPUWithExistingWorkflow -Integration $integration
        if ($integrateResult) {
            Write-ECRRLog "GPU integration completed successfully"
        } else {
            Write-ECRRLog "GPU integration failed" "ERROR"
            exit 1
        }
    }
    "validate" {
        # ECRR: Examine
        $validation = Validate-GPUIntegration
        if ($validation.score -ge 80) {
            Write-ECRRLog "GPU integration validation: PASSED ($($validation.score.ToString('F1'))%)"
            exit 0
        } else {
            Write-ECRRLog "GPU integration validation: FAILED ($($validation.score.ToString('F1'))%)" "ERROR"
            exit 1
        }
    }
    "deploy" {
        # ECRR: Clean
        $deployResult = Deploy-GPUIntegration
        if ($deployResult) {
            Write-ECRRLog "GPU integration deployment completed successfully"
        } else {
            Write-ECRRLog "GPU integration deployment failed" "ERROR"
            exit 1
        }
    }
    "monitor" {
        # ECRR: Report
        Start-GPUIntegrationMonitoring
        Write-ECRRLog "GPU integration monitoring started"
    }
    "report" {
        # ECRR: Report
        $report = Generate-GPUIntegrationReport
        Write-ECRRLog "GPU integration report generated"
    }
    "cleanup" {
        # ECRR: Clean
        $cleanupResult = Cleanup-GPUIntegration
        if ($cleanupResult) {
            Write-ECRRLog "GPU integration cleanup completed successfully"
        } else {
            Write-ECRRLog "GPU integration cleanup failed" "ERROR"
            exit 1
        }
    }
}

# ECRR: Report
$reportFile = "artifacts/gpu-integration-automation-$(Get-Date -Format 'yyyyMMdd_HHmmss').json"
$ECRRReport | ConvertTo-Json -Depth 5 | Out-File -FilePath $reportFile -Encoding UTF8
Write-ECRRLog "ECRR report saved to: $reportFile"

Write-Host "`n🔗 GPU Integration Automation Complete" -ForegroundColor Green
Write-Host "ECRR Report: $reportFile" -ForegroundColor Cyan
