#Requires -Version 7.0

<#
.SYNOPSIS
    Set up Windows Task Scheduler job for SigNoz canary monitoring with alerting.

.DESCRIPTION
    Creates a scheduled task that runs the SigNoz canary monitor every 15 minutes
    and sends alerts when the status is not healthy. Includes error handling
    and logging capabilities.

.PARAMETER TaskName
    Name for the scheduled task (default: "SigNoz-Canary-Monitor").

.PARAMETER IntervalMinutes
    Interval between runs in minutes (default: 15).

.PARAMETER EmailAlert
    Email address for alerts (optional).

.EXAMPLE
    .\setup-canary-monitoring-schedule.ps1
    Sets up monitoring every 15 minutes with default settings.

.EXAMPLE
    .\setup-canary-monitoring-schedule.ps1 -IntervalMinutes 30 -EmailAlert "admin@company.com"
    Sets up monitoring every 30 minutes with email alerts.
#>

param(
    [string]$TaskName = "SigNoz-Canary-Monitor",
    [int]$IntervalMinutes = 15,
    [string]$EmailAlert = $null
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Write-Success {
    param([string]$Message)
    Write-Host "[OK]    $Message" -ForegroundColor Green
}

function Write-WarnMsg {
    param([string]$Message)
    Write-Host "[WARN]  $Message" -ForegroundColor Yellow
}

function Write-Failure {
    param([string]$Message)
    Write-Host "[FAIL]  $Message" -ForegroundColor Red
}

function Write-Info {
    param([string]$Message)
    Write-Host "[INFO]  $Message" -ForegroundColor Cyan
}

$ScriptDir = $PSScriptRoot
$MonitorScript = Join-Path $ScriptDir "monitor-signoz-canary.ps1"
$LogDir = Join-Path $ScriptDir "..\artifacts"
$LogFile = Join-Path $LogDir "canary-monitor-schedule.log"

# Ensure artifacts directory exists
if (-not (Test-Path $LogDir)) {
    New-Item -Path $LogDir -ItemType Directory | Out-Null
}

Write-Info "Setting up SigNoz canary monitoring schedule..."
Write-Info "Task Name: $TaskName"
Write-Info "Interval: $IntervalMinutes minutes"
Write-Info "Monitor Script: $MonitorScript"

try {
    # Check if monitor script exists
    if (-not (Test-Path $MonitorScript)) {
        throw "Monitor script not found: $MonitorScript"
    }

    # Create the PowerShell action script
    $ActionScript = @"
# SigNoz Canary Monitor Scheduled Action
# Generated by setup-canary-monitoring-schedule.ps1

Set-Location '$ScriptDir'
`$LogFile = '$LogFile'
`$Timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'

try {
    # Run the monitor script
    `$ExitCode = & '$MonitorScript'
    
    # Log the result
    `$Status = switch (`$ExitCode) {
        0 { 'HEALTHY' }
        1 { 'WARNING' }
        2 { 'CRITICAL' }
        3 { 'ERROR' }
        default { 'UNKNOWN' }
    }
    
    `$LogEntry = "`$Timestamp - Exit Code: `$ExitCode, Status: `$Status"
    Add-Content -Path `$LogFile -Value `$LogEntry
    
    # Send alert if not healthy
    if (`$ExitCode -ne 0) {
        `$AlertMessage = "SigNoz Canary Monitor Alert: Status=`$Status, ExitCode=`$ExitCode, Time=`$Timestamp"
        Write-Host `$AlertMessage -ForegroundColor Red
        
        # Email alert if configured
        if ('$EmailAlert' -and '$EmailAlert' -ne '') {
            try {
                Send-MailMessage -To '$EmailAlert' -Subject "SigNoz Canary Alert" -Body `$AlertMessage -SmtpServer "localhost"
            } catch {
                Write-Host "Failed to send email alert: `$(`$_.Exception.Message)" -ForegroundColor Yellow
            }
        }
    }
    
    exit `$ExitCode
} catch {
    `$ErrorMsg = "Scheduled monitor failed: `$(`$_.Exception.Message)"
    Add-Content -Path `$LogFile -Value "`$Timestamp - ERROR: `$ErrorMsg"
    Write-Host `$ErrorMsg -ForegroundColor Red
    exit 3
}
"@

    $ActionScriptPath = Join-Path $ScriptDir "canary-monitor-action.ps1"
    $ActionScript | Out-File -FilePath $ActionScriptPath -Encoding UTF8

    # Remove existing task if it exists
    $ExistingTask = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($ExistingTask) {
        Write-Info "Removing existing task: $TaskName"
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    }

    # Create the scheduled task
    $Action = New-ScheduledTaskAction -Execute "pwsh.exe" -Argument "-File `"$ActionScriptPath`""
    $Trigger = New-ScheduledTaskTrigger -Once -At (Get-Date) -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes) -RepetitionDuration (New-TimeSpan -Days 365)
    $Settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable -RunOnlyIfNetworkAvailable
    $Principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest

    Register-ScheduledTask -TaskName $TaskName -Action $Action -Trigger $Trigger -Settings $Settings -Principal $Principal -Description "SigNoz Canary Monitoring - Runs every $IntervalMinutes minutes"

    Write-Success "Scheduled task '$TaskName' created successfully!"
    Write-Info "Task will run every $IntervalMinutes minutes"
    Write-Info "Log file: $LogFile"
    
    if ($EmailAlert) {
        Write-Info "Email alerts configured for: $EmailAlert"
    } else {
        Write-WarnMsg "No email alerts configured - alerts will only appear in logs"
    }

    # Show task details
    $Task = Get-ScheduledTask -TaskName $TaskName
    Write-Info "Task Status: $($Task.State)"
    Write-Info "Next Run Time: $($Task.NextRunTime)"

} catch {
    $ErrorMsg = "Failed to set up scheduled monitoring: $($_.Exception.Message)"
    Write-Failure $ErrorMsg
    throw
}
