// Extract trending #tags from local ledger and optional offline dumps; emit metrics + suggestions.
// Usage: tsx scripts/social/trends.ts --out artifacts/social/trends.json --suggest docs/social/TAGS.suggestions.yaml --since 14
import { promises as fs } from 'fs';
import path from 'path';

const now = () => new Date().toISOString();
const arg = (k:string, d?:string) => { const i = process.argv.indexOf(`--${k}`); return i>-1 ? process.argv[i+1] : d; };
const OUT = arg('out','artifacts/social/trends.json')!;
const SUG = arg('suggest','docs/social/TAGS.suggestions.yaml')!;
const DAYS = parseInt(arg('since','14')!,10);

type Trend = { tag:string; count:number; sample?:string[]; };

function withinDays(ts:string){ const d = Date.parse(ts||''); return isFinite(d) && (Date.now()-d) <= DAYS*86400_000; }
function scanTags(text:string){ const m = text.match(/#([A-Za-z][\w-]{0,48})/g)||[]; return m.map(s=>s.slice(1).toLowerCase()); }

async function readPosted(){
  try {
    const lines = (await fs.readFile('artifacts/social/posted.jsonl','utf8')).trim().split('\n');
    return lines.map(l => JSON.parse(l)).filter(x => x.postedAt ? withinDays(x.postedAt) : true);
  } catch { return []; }
}

(async () => {
  if (await fs.stat('.agent/LOCK').then(()=>true).catch(()=>false)) process.exit(50);
  await fs.appendFile('.agent/EVIDENCE.log', JSON.stringify({t:now(),who:'A',type:'plan',lane:'SOCM',msg:`trends since ${DAYS}d`})+'\n');

  const posts = await readPosted();
  const map = new Map<string,Trend>();
  const push = (tag:string, url?:string) => {
    const t = map.get(tag) ?? { tag, count:0, sample:[] };
    t.count += 1; if (url && t.sample!.length<3) t.sample!.push(url);
    map.set(tag, t);
  };

  for (const p of posts) {
    for (const t of scanTags(p.text||'')) push(t, p.bskyUri ? `https://bsky.app/profile/${p.handle||'resonai.bsky.social'}/post/${String(p.bskyUri).split('/').pop()}` : undefined);
  }

  const trends = [...map.values()].sort((a,b)=>b.count-a.count);
  await fs.mkdir(path.dirname(OUT), { recursive:true });
  await fs.writeFile(OUT, JSON.stringify({ generatedAt:now(), days:DAYS, total:posts.length, trends }, null, 2), 'utf8');

  // Emit suggestions file (append-only; humans decide what to add to TAGS.yaml)
  const suggestions = ['# Generated by trends.ts — review before applying\napproved_proposals:\n'];
  for (const t of trends.slice(0,8)) {
    if (t.count < 2) continue; // threshold: at least 2 mentions locally
    suggestions.push(`  - tag: ${t.tag}\n    rationale: "Local frequency ${t.count} in ${DAYS}d; co-occurs with project themes"\n    samples:${(t.sample||[]).map(u=>`\n      - ${u}`).join('') || ' []'}\n`);
  }
  await fs.writeFile(SUG, suggestions.join(''), 'utf8');

  await fs.appendFile('.agent/EVIDENCE.log', JSON.stringify({t:now(),who:'A',type:'report',lane:'SOCM',msg:`trends -> ${OUT}; suggestions -> ${SUG}`})+'\n');
  await fs.appendFile('.agent/EVIDENCE.log', JSON.stringify({t:now(),who:'A',type:'exit',lane:'SOCM',msg:'ok'})+'\n');
})();

