import { describe, expect, it } from "vitest";
import { KPICalculator } from "../../src/dashboard/kpi-calculator";

type TaskFilter = Record<string, any> | undefined;

const createMockDb = () => ({
  async getReportCount(filter?: Record<string, any>) {
    if (filter?.status === "Open") {
      return 4;
    }
    return 10;
  },
  async getTaskCount(filter?: TaskFilter) {
    if (!filter) {
      return 20;
    }
    if (filter?.slaDueAt) {
      return 2;
    }
    if (filter?.state?.$nin) {
      return 6;
    }
    if (filter?.["meta.autoGenerated"] === true) {
      return 12;
    }
    if (filter?.createdAt) {
      return 15;
    }
    return 0;
  },
  async getTimeToTaskSamples() {
    return [{ timeToTask: 4 }];
  },
  async getTotalTaskDuration() {
    return 120;
  },
  async getTaskCountByPriority() {
    return { high: 3, medium: 5 };
  },
  async getTaskCountByState() {
    return { open: 6, done: 14 };
  },
  async getTaskCountByAssignee() {
    return { alice: 5, bob: 7 };
  },
  async getUsers() {
    return [{ id: "alice", maxWip: 4 }, { id: "bob", maxWip: 6 }];
  },
  async getEventCount() {
    return 3;
  },
} as const);

describe("KPICalculator", () => {
  it("computes overview metrics including automation coverage", async () => {
    const calculator = new KPICalculator(createMockDb() as any);

    const overview = await calculator.calculateOverview();

    expect(overview.totalReports).toBe(10);
    expect(overview.openReports).toBe(4);
    expect(overview.totalTasks).toBe(20);
    expect(overview.openTasks).toBe(6);
    expect(overview.overdueTasks).toBe(2);
    expect(overview.automationCoverage).toBeCloseTo(80);
  });
});
